# Generated by Django 5.1.6 on 2025-03-08 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question_1', models.CharField(choices=[('first_pet', 'What was the name of your first pet?'), ('mother_maiden', 'What is your mother’s maiden name?'), ('first_car', 'What was the model of your first car?')], max_length=50)),
                ('security_answer_1', models.CharField(max_length=255)),
                ('security_question_2', models.CharField(choices=[('first_pet', 'What was the name of your first pet?'), ('mother_maiden', 'What is your mother’s maiden name?'), ('first_car', 'What was the model of your first car?')], max_length=50)),
                ('security_answer_2', models.CharField(max_length=255)),
                ('security_question_3', models.CharField(choices=[('first_pet', 'What was the name of your first pet?'), ('mother_maiden', 'What is your mother’s maiden name?'), ('first_car', 'What was the model of your first car?')], max_length=50)),
                ('security_answer_3', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
