# Generated by Django 5.1.6 on 2025-03-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='security_question_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='security_question_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='security_question_3',
            field=models.CharField(max_length=50),
        ),
    ]
