# Generated by Django 5.1.6 on 2025-03-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rental',
        ),
    ]
