# Generated by Django 5.1.6 on 2025-03-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_message_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
