# Generated by Django 5.1.6 on 2025-03-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
