# Generated by Django 5.1.6 on 2025-03-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
