# Generated by Django 5.1.6 on 2025-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available_dates',
            field=models.JSONField(default=list),
        ),
    ]
