# Generated by Django 5.1.7 on 2025-03-26 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_booking_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='car',
            name='available_dates',
        ),
        migrations.AddField(
            model_name='car',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='available_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
