# Generated by Django 5.1.7 on 2025-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_remove_car_availability_remove_car_available_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='car',
            name='available_to',
        ),
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='available_dates',
            field=models.JSONField(default=list),
        ),
    ]
