# Generated by Django 5.1.7 on 2025-04-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car'),
            preserve_default=False,
        ),
    ]
