# Generated by Django 5.1.6 on 2025-03-14 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewee',
            new_name='reviewed_user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewed_user')},
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='car',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
    ]
