# Generated by Django 5.1.6 on 2025-03-14 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_review_unique_together_review_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewed_user')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='car',
        ),
    ]
