# Generated by Django 5.1.7 on 2025-03-26 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_remove_car_availability_remove_car_available_dates_and_more'),
        ('notifications', '0007_alter_review_unique_together_review_car_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='review',
            to='cars.booking'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='car',
        ),
    ]
