# Generated by Django 5.1.7 on 2025-03-26 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_car_available_from_remove_car_available_to_and_more'),
        ('notifications', '0008_alter_review_unique_together_review_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.booking'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'booking')},
        ),
    ]
